# Generated by Django 4.0.2 on 2022-02-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
    ]
